apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
  namespace: tabimworld-prod
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-depl
  template:
    metadata:
      labels:
        app: backend-depl
    spec:
      containers:
        - name: headless
          image: ghcr.io/tabimworld/backend:latest
          envFrom:
            - secretRef:
                name: backend-env
            - configMapRef:
                name: backend-env
